### ISSUE TITLE
Encryption Key Generated

### ISSUE THREAD

**Issue by aziz42424** [lastpass/lastpass-cli#114]
Dear Copeland,

Nice to discuss LastPass features again with you.

To login with my Account in LastPass, I might use the official website, Browser Plugins or command line version. I just wonder if all three ways generating the same decryption key to decrypt the content? I know that encrypted content is saved in different location based on the version and OS, But what about the decryption key for the three types? are they the same?

Regards
Abdulla

**Comment by bcopeland** [comment]
On Sat, Aug 22, 2015 at 12:37:12PM -0700, aziz42424 wrote:
> Dear Copeland,
> 
> Nice to discuss LastPass features again with you.
> 
> To login with my Account in LastPass, I might use the official website, Browser Plugins or command line version. I just wonder if all three ways generating the same decryption key to decrypt the content? I know that encrypted content is saved in different location based on the version and OS, But what about the decryption key for the three types? are they the same?

Yes the encryption key generated is the same, otherwise you wouldn't
be able to open your vault on another computer with a different program.

Look at kdf.c, the key is derived from the master password using pbkdf2-sha256.


-- 
Bob Copeland %% http://bobcopeland.com/

**Comment by aziz42424** [comment]
So when I supply my username and Master password, it is derive the key from combining username, MasterPassword, Iteration and kdf_hash_len. Thats OK for me. There are different thoughts I think about while reviewing the code:
1) LastPass is removing the decryption key from memory immediately after process success (mlock)? 2) LastPass still recognize the active user by managing the agent session (Agent.c) . That why it doesn’t request my credentials every time?
3) After generating the decryption key, where is the method to decrypt the content/Vault?

Thanks for your help.

**Comment by bcopeland** [comment]
mlock() doesn't remove things from memory, it actually pins it into memory.  The purpose of that is so the key doesn't leak out into swapfiles.  The key is still around which is why the agent doesn't require your credentials every time.

The decryption code is called from blob.c, see `read_crypt_string`.  I know it's kind of a cop-out as we don't really have any source documentation, but my suggestion is to "use the source" -- all the answers are there, somewhere.

I don't really think github issues is the right forum for this -- this is for bug reports, so I'm going to close it.
