### ISSUE TITLE
lpass add: Folder name has improper format 

### ISSUE THREAD

**Issue by TKonczynski** [lastpass/lastpass-cli#187]
why do I get this error message when using lpass add? 

Is this because one of my folders is read-only?
Is this because the name of one of the folders contains spaces?
How can I change this presumably incorrect folder to another one?
Maybe I'm just using `lpass add` incorrectly? What I'm typing is: `lpass add --notes myinput` Why does it return the usage examples if I type  `lpass add --notes myinput NAMEOFTHENEWENTRY` if the usage itself says this is the correct format?

I hope the questions aren't too obvious; lpass really seems like an easy tool, but IMO the documentation is insufficient, what it lacks is the usage examples.

Many thanks, 
TK

**Comment by bcopeland** [comment]
What is the value of `myinput` in your example?  Typing that verbatim works here.  Appending `NAMEOFTHENEWENTRY` doesn't work because `myinput` already *is* the name of the new entry.

I believe the error you are encountering was fixed in b6c89d8b934c.

Patches to improve the docs would be most welcome.

**Comment by TKonczynski** [comment]
`myinput` being my note that I want to create in my account. OK; I guess I get it now, thanks for your feedback

**Comment by bcopeland** [comment]
My guess is you are running something other than the tip of tree?   That error string no longer exists in the repository.  Unfortunately the fix has not landed in a release yet (to be rectified in the next day or so). 

The incantation for storing a note in once shot is something like ```echo "mynote" | lpass add --notes --non-interactive folder/itsname``` -- note that you need the ```folder/``` part due to the aforementioned bug, or you need to pull down the latest code.

**Comment by TKonczynski** [comment]
Bob,
Thanks for the hints, much appreciated. I will test this soon and see if it works.

**Comment by TKonczynski** [comment]
Ok, and now it works 👍  Thank you once again!
