### ISSUE TITLE
Query field list for an entry?

### ISSUE THREAD

**Issue by fortes** [lastpass/lastpass-cli#208]
Is it possible to get the list of fields for an entry? I don't always remember the exact name of a field, which means I have to call `show` for the entire entry to find the name (which outputs sensitive info as well).

Would be great to allow bash completion on the field as well.

**Comment by bcopeland** [comment]
At present, no, but that would be a nice feature.  Maybe something like `lpass show --field-names-only`.

**Comment by fortes** [comment]
`lpass show --field-names` would work, and then we could add into completion when using `--field`

**Comment by bcopeland** [comment]
OK, I went another way on this.  It's not quite as simple as the proposed `lpass show --field-names`, but since user-supplied formatting has been on my TODO forever, I did a proof of concept to see whether that could be used for this use-case as well.

So, check out https://github.com/lastpass/lastpass-cli/tree/topic-user-format-strings and specifically e1036e22b429e33e09d544af823f6eac307b9e69 and let me know what you think.

**Comment by fortes** [comment]
The tab completion works great, but it seems to prompt me for my password again when doing tab completion (but not if I do a normal `show` command)

**Comment by bcopeland** [comment]
Whoops, forgot to remove the "./" from the "./lpass" in the bash completion script from testing.

I force-pushed the fix, feel free to pull and try again.

**Comment by fortes** [comment]
Pulled latest and it works beautifully, thanks!

**Comment by bcopeland** [comment]
Ok, this has since been merged, closing.
