### ISSUE TITLE
auto logout

### ISSUE THREAD

**Issue by hoto** [lastpass/lastpass-cli#254]
Hi,

Is there some way that after `lpass login` lpass cli would logout automatically after some period of time?
Is this configurable?

Because if I forget to `lpass logout` then the machine I used `lpass login` will become a vulnarability as the cli will never ask for master password or 2MFA code and will work indefinitely, is this true?

What I would like is something like:

`lpass login myuser@example.com --auto-logout 24h`
or
`lpass login myuser@example.com --valid 24h`

Or an option in the cli that would auto log out if lpass cli was not used for a specified period of time, for example:

`lpass logout --after-inactivity 24h`

btw I really like this small app ;)

**Comment by bcopeland** [comment]
On Tue, Jan 17, 2017 at 04:32:19AM -0800, Andrzej Rehmann wrote:
> Hi,
> 
> Is there some way that after `lpass login` lpass cli would logout automatically after some period of time?
> Is this configurable?
> 
> Because if I forget to `lpass logout` then the machine I used `lpass login`
> will become a vulnarability as the cli will never ask for master password or
> 2MFA code and will work indefinitely, is this true?

The 2fa code is not reprompted, but you will have to re-enter your
master password after LPASS_AGENT_TIMEOUT (default 1 hour) in order
to access the vault.  This is because the agent, which keeps the
decryption key in memory, exits after that period of time, and so
it would be impossible for the lpass command to retrieve entries from
that point on.

The difference between that and logout is that logout _also_ deletes
the cached copy of the encrypted vault.

I don't think there's sufficient reason to add a new option for
auto-logout, and even if we wanted to, a bit complicated because there's
no running executable to trigger this.  What you could do instead (if,
for some reason, the above in insufficient) is just delete the config
directory in a cronjob (config is either in ~/.lpass or ~/.config/lpass).

**Comment by hoto** [comment]
I did not know that after 1h by default you will have to enter the password again.
This solves it for me.

I just started using lastpas cli today, so did not had a chance to use it after 1h. It really does ask for master password again ;)

Thanks @bcopeland
