### ISSUE TITLE
avoid aliases?

### ISSUE THREAD

**Issue by hymie0** [lastpass/lastpass-cli#261]
If I set up an alias for the `show` command ... is there a way that I can run `lpass show` and get the "real" `show` command and not my alias?

(The source code implies "no, aliases are absolute", but maybe I'm missing it.)

**Comment by bcopeland** [comment]
On Sat, Jan 21, 2017 at 12:02:48PM -0800, hymie0 wrote:
> If I set up an alias for the `show` command ... is there a way that I can run
> `lpass show` and get the "real" `show` command and not my alias?
> 
> (The source code implies "no, aliases are absolute", but maybe I'm missing
> it.)

No, aliases are absolute.  It's probably best to use different names for
your aliases to avoid this issue.  In the git world (where I borrowed this
feature from), they don't even allow aliases to override builtins due to
the potential for confusion.
