### ISSUE TITLE
JSON export

### ISSUE THREAD

**Issue by jantman** [lastpass/lastpass-cli#263]
The ``export`` switch is nice with its CSV, but it would be very useful for scripting if this program offered some better machine-readable output format, such as JSON. This would be useful not only for export but also for regular show operations, such as ``lpass show --json UNIQUE-ID``.

**Comment by bcopeland** [comment]
You can use the `--format` switch to customize the output for `lpass show`.

I'd rather not bloat the code with yet another output format -- if you want json, you might take a look at csvkit which includes a command-line csv-to-json converter that you could just insert in a pipeline.

**Comment by kyleburton** [comment]
I'd like to +1 this, having a machine readable format that preserves the fidelity of the data in lastpass is something I'm currently trying to wrap around the output of this tool in order to automate the management (i.e. rotation) of secrets and configuration.  The csv export doesn't preserve newlines in notes and certificates, having the ability to export and import JSON would be ideal.  Alternatively if this tool were broken into a library and the cli wrapper I'd be happy to wrap that functionality around the library on my own.

**Comment by grepler** [comment]
+1 for this as well. Similar to Kyle, I'm trying to wrap this tool's output to manage encryption keys.

**Comment by bcopeland** [comment]
@kyleburton @grepler OK, if someone can propose a JSON output format that doesn't add too many lines of code, we can see about incorporating one such.

As for turning lastpass-cli into a library... I'm not really opposed in principle, but a lot of the things it does are not very library-like (such as reading files, spawning processes, etc.)  It might be difficult to come up with a subset of functionality that is generally palatable to people.

**Comment by kyleburton** [comment]
I'd see the file-handling as remaining in the `main`, all of the read/write functionality.  While the library focused on the http functionality (essentially the RPC API), working with the blob, parsing and encryption functionality.  If that were a lib, then it could be integrated into other languages more easily (my use case at $work has me wrapping this tool's stdout, a lib would have meant direct integration w/the structs).  I do think it'd be a large change though.

**Comment by nneul** [comment]
@bcopeland I found this issue when searching prior to putting in my own asking if you'd take a PR adding the functionality. 

I'd be interested in implementing json variants of "ls", "show" and "export".

In order to minimize the impact on existing code, I was intending to either A) have an explicitly visible json variant of the command ("ls-json") or to enhance the commands[] handling in lpass.c to look at "--json" option and pick an internal (hidden) variant of the command that output in json format. This _would_ effectively duplicate each of the 'cmd-X.c' files for those functions, but it would be much less invasive. 

Ideally, I'd like to add optional dependency on either yajl or cjson.

Eventually I'd like to have 'add' and 'edit' support this as well.

If you would be amenable to accepting a MR for that, I'll get something put together.

**Comment by bcopeland** [comment]
nneul, I think --json could be ok, and I would accept a PR for this.  I'm looking into switching to all JSON endpoints for the next version so we could swap libxml for whatever json library makes the most sense (at first blush, I'd say yajl over cjson).

**Comment by bcopeland** [comment]
@nneul just FYI I did a test integration of YAJL with cmake in topic/json-poc branch, in case that helps (the travis build fails because I didn't add it as a dependency yet, but the tree parser is working).

**Comment by bcopeland** [comment]
FYI this version pushed:
 - does not use YAJL, though I think it would be good in a future update, especially if we start adding support for json endpoints;
 - does not implement `export --json`, because there is no `import --json` ... but if you want to export everything you can use `show -jxG .*`
