### ISSUE TITLE
lpass import question

### ISSUE THREAD

**Issue by RobertKaldenbach** [lastpass/lastpass-cli#268]
I was looking at the lpass import functionality and I have realized that there is a difference in logic with it and the lpass add function. 

I am able to use lpass add to add the same account to two different folders.  

lpass import will detect the account in the other folder and prevent the account from being added to a second folder.  This also appears to cause issues for us to be able use lpass import from loading a back up as well.

Which logic should we be following?  Does lastpass not want us to have duplicate accounts even if they are in different shared folders?

Thanks in advance!

**Comment by RobertKaldenbach** [comment]
Just to follow up.  The lpass import feature also did not load the sites back into their shared folder but created a new folder.  Is that the expected behavior?

**Comment by bcopeland** [comment]
On Sun, Feb 19, 2017 at 08:40:56AM -0800, Robert Kaldenbach wrote:
> Which logic should we be following?  Does lastpass not want us to have
> duplicate accounts even if they are in different shared folders?

The reason I added the dedupe was so that you could run import multiple
times from the same CSV without worrying about getting the same account
created twice.  Right now, the account name, password, url, and username
are used for duplicate comparisons.

In order to fix this issue, I think we just need to include group as well.

**Comment by bcopeland** [comment]
On Mon, Feb 20, 2017 at 07:17:46AM -0800, Robert Kaldenbach wrote:
> Just to follow up.  The lpass import feature also did not load the sites back into their shared folder but created a new folder.  Is that the expected behavior?

Hmm, I'm not sure how we should try to handle shared folders.  They will need
to be encrypted with the share key which implies that we need to do multiple
uploads instead of a single upload, and things like permissions will get lost
since they cannot be represented in the CSV.  Perhaps we should not try to
import them at all?

**Comment by RobertKaldenbach** [comment]
Perhaps We shouldn't import into shared folders.    The case I had on Friday was that I backed up our company main shared folder removed credentials  from the folder and attempted to import them back into the folder.  Two strange things happened.

1.) The sites that were in the shared folder were imported into a non shared folder.

2.) The lastpass firefox plugin showed that the imported sites were imported into the shared folder even though they were actually imported into a non shared folder.  This caused some confusion of where the sites were actually located in my vault.

When I figured out where the sites actually were I was able to move them with no issue.  So I might take a look at using lpass mv after the import to come up with a work around.  Perhaps move the folder I created into the shared folder.   I'll take a look later today and see if that can solve my problem.  

Also just to clarify I did not remove the actual shared folder from the vault only the sites in the folder so I don't think I should have to worry about permissions?

**Comment by bcopeland** [comment]
Sites in a shared folder can have additional permissions applied to them on a per-site, per-user basis, through `lpass share limit`.  Because these are based on account id, if you import them and thus create a new account id for the duplicate, the new account may not be limited in the same way.

I think I'll just make `lpass import` skip shared folders to minimize confusion; if someone wants that, then we can do the work then, with an additional command-line arg to encrypt with the share key and upload them in a separate batch.
