### ISSUE TITLE
Max Sync Calls?

### ISSUE THREAD

**Issue by throck95** [lastpass/lastpass-cli#390]
I've been messing around with the cli interface via an Ubuntu VM to try and see if I could create an auto-password change for my banking password to continuously update it and keep the password changing. I've noticed, however, when I make changes and attempt to sync them, they don't always post to my account.

Is there a period of time associated to how frequently the server will accept sync calls?

**Comment by bcopeland** [comment]
Until very recently, if you did this, it hit a bad corner case on the server that would cause your vault to balloon and then requests start timing out due to it not fitting in caches anymore.  If you provide me or support your account name, we can schedule a gc task on your account to clean that up.

**Comment by throck95** [comment]
So would developing a RPA and script to perform a password change and update, say for example, every 15 minutes feasible? Or would that ultimately cause this cache problem to occur each time?

**Comment by bcopeland** [comment]
The problem is that you can accumulate a lot of (worthless) history records for that site, so it will still be large -- I would probably do it every 1 hr if it were me.  But the growth pattern is much more stable now so 15 minutes might be manageable.  You would still need to ask support to have your current blob rebuilt since it is probably already too large for caching and, while we do automatically clean up the logs eventually, it might take some time for that to happen.

**Comment by throck95** [comment]
I've already submitted a support ticket to have it rebuilt. Ticket #: 72E2SA4ZJSCQ

That having been said, 60 minutes seems feasible for a first pass. I'm still trying to reach out to my bank to understand if RPA password change would cause problems within their system or not.
