### ISSUE TITLE
Bulk Attachment export

### ISSUE THREAD

**Issue by mindrunner** [lastpass/lastpass-cli#412]
Hi Folks,
since it is a long term missing feature to export all attachments, I wrote a script around lastpass-cli to do so.

https://github.com/mindrunner/lastpass-attachment-exporter

Maybe we can integrate this somewhere upstream?
Cheers

**Comment by thibaultmol** [comment]
Please lastpass, add this feature! It's insane that your chrome extension and website NEITHER support a FULL export of one's account (including attachments). At Least implement it in the official CLI.....
(I'm a paying for a 5 user license for Lastpass Teams.... )

**Comment by mindrunner** [comment]
Haha, they seriously locked the thread? I really consider migrating somewhere else. Unfortunately all the alternatives have some flaws as well...

**Comment by bcopeland** [comment]
At the very least the shell script could be merged into contrib.  @rutkai ?

**Comment by rutkai** [comment]
I'm going to look into it tomorrow.

**Comment by rutkai** [comment]
@mindrunner could you submit a PR with the files into the contrib folder? In this way we can put the script into the upstream.

**Comment by mindrunner** [comment]
Thank you! :)

https://github.com/lastpass/lastpass-cli/pull/419

**Comment by fragolinux** [comment]
in case someone is interested, i tried to fix all the issues in the export script (problems running on macos because of sed/gsed, spaces in filenames, multilines in csv, unavaliability of full json export, etc) in this fork, where i took over the work done by watson81, rebased on latest official code from main repo, and added full online build (the win one still fails...) of all the relevant binaries and docker images, too...
you can now run everything from docker, i added this script too, which imports everything exported to json, into a keepassxc kbdx file, all fully organized and with attachments included, tons of logs of every operation are generated, when some import fail they're converted to base64, and much more, please take a look at the readme here for more details...
https://github.com/fragolinux/lastpass-cli/tree/master/keepass
