### ISSUE TITLE
Feature Request: Tab completion for entries

### ISSUE THREAD

**Issue by rothgar** [lastpass/lastpass-cli#54]
Please add tab completion for entries. Similar to [pass](http://www.passwordstore.org/) which has tab completion for folders and entries. When dealing with 100s of entries it is pretty essential to make using the cli useful.

It'd also be great if tab completion worked with fuzzy logic so names didn't have to be exact.

Please see pass' [bash completion](http://git.zx2c4.com/password-store/tree/src/completion/pass.bash-completion) for more details, but I'm sure you guys can figure out a way. ;)

**Comment by RowanKaag** [comment]
Is this merged yet? Doesn't seem to work on OSX 10.11.1

**Comment by bcopeland** [comment]
No, it is still unmerged, and still somewhat broken due to improper escaping.

**Comment by bcopeland** [comment]
Merged now.

**Comment by RowanKaag** [comment]
excuse my (probably stupid) question, but in what context was the merge supposed to work? I might be entering wrong commands to try the autocomplete, but typing lpass log; and then pressing tap, isn't that supposed to autocomplete to login?

**Comment by bcopeland** [comment]
You need to load it into your bash session, e.g.:
```
source contrib/lpass_bash_completion
```

**Comment by RowanKaag** [comment]
I've installed via Homebrew, ```which lpass``` returns /usr/local/bin, can't find any shell scripts in there. Nor can I find any in /usr/local/Cellar/. Any idea how I could add a line in .zshrc to make it a default for every new shell?

**Comment by bcopeland** [comment]
It's in the github repository; as I didn't do the homebrew build, I'm not sure where it might have contrib scripts.

If you are using zsh, it probably will not work for you.  If using bash, you could just add the ```source /path/to/lpass_bash_completion``` to your ~/.bashrc.  Unfortunately I don't use zsh so I don't know much about how completion works for it.

**Comment by timja** [comment]
To anyone else that comes across this from google and is using homebrew:

```
find $(brew --prefix) -type f -name lpass
```

Mine was in:
```
/usr/local/Cellar/lastpass-cli/1.0.0/share/bash-completion/completions/lpass
```

**Comment by SamHH** [comment]
@timja This worked for me with 1.0.0, but on 1.1.1 there's no `bash-completion` directory. Just me or you as well?

**Comment by timja-kainos** [comment]
@SamHH Missing for me to. I hadn't noticed because the `brew update` kept around the old version
```
$ find $(brew --prefix) -type f -name lpass
/usr/local/Cellar/lastpass-cli/1.0.0/bin/lpass
/usr/local/Cellar/lastpass-cli/1.0.0/share/bash-completion/completions/lpass
/usr/local/Cellar/lastpass-cli/1.1.1/bin/lpass
```

**Comment by bcopeland** [comment]
On Mon, Jan 16, 2017 at 07:34:56AM -0800, Tim Jacomb wrote:
> @SamHH Missing for me to. I hadn't noticed because the `brew update` kept around the old version
> ```
> $ find $(brew --prefix) -type f -name lpass
> /usr/local/Cellar/lastpass-cli/1.0.0/bin/lpass
> /usr/local/Cellar/lastpass-cli/1.0.0/share/bash-completion/completions/lpass
> /usr/local/Cellar/lastpass-cli/1.1.1/bin/lpass
> ```

This is because the build system is now cmake based, and I had no idea
where completions should actually go on OSX (on Linux, this would come
from `pkg-config --variable=completionsdir bash-completion`).

I guess we could default to that (share/bash-completions), but if someone
knows better how it should actually be determined, I'd love to know.

**Comment by timja-kainos** [comment]
I believe the location it should actually be going into is:
```
 $(brew --prefix)/etc/bash_completion.d
```

**Comment by ssalonen** [comment]
There was some discussion for zsh autocompletion. 

For the record, bash completions are supported in `zsh` using `bashcompinit`. For more information, consult these instructions: 

https://stackoverflow.com/questions/3249432/i-have-a-bash-tab-completion-script-is-there-a-simple-way-to-use-it-from-zsh

For me the following seems to work in `~/.zshrc` (fedora installation)

```bash
# support bash autocompletion
# https://stackoverflow.com/questions/3249432/i-have-a-bash-tab-completion-script-is-t
autoload bashcompinit
bashcompinit

if [[ -f /usr/share/bash-completion/completions/lpass ]]; then
        source /usr/share/bash-completion/completions/lpass
fi
```

**Comment by rderik** [comment]
Just as an FYI, I got my pull-request to the Homebrew formula for lastpass-cli to now install bash_completion and completion for fish by default when you install it. 

So if you have already installed lastpass-cli you'll have to manually reinstall because the version of the formula wasn't changed.

https://github.com/Homebrew/homebrew-core/pull/24745#issuecomment-370252870

Hope that helps

**Comment by tbigueres** [comment]
Hi, 

Any news on this ? 
I have the same issue, on mac OS High Sierra and lastpass CLI 1.3.0. 

Is there any way to get auto-completion for mac ? 
Thanks

**Comment by rderik** [comment]
Hi @tbigueres,

If you install it through homebrew you should now have the auto-completion by default. 

If you previously had lastpass cli installed  the version didn't change so it doesn't apply if you do a update you'll have to manually uninstall and reinstall it again for it to get the auto-completion.

Have you tried that?

**Comment by tbigueres** [comment]
Hey @rderik 

Thanks for the quick answer. 
Indeed I tried 

`brew reinstall lastpass-cli`

But it did not work. I still cannot use autocompletion. 
If you have any idea it would be awesome.

**Comment by rderik** [comment]
I just try it now I did:
`brew uninstall lastpass-cli`
then 
`brew install lastpass-cli`
Then open a new bash terminal and
`lpass log[tab]`
and got
login logout

What version of bash are you on?
`echo $BASH_VERSION`

**Comment by tbigueres** [comment]
I'm on ZSH, 
A colleague of mine has the same issue and is on the following bash : 

`echo $BASH_VERSION
3.2.57(1)-release`

**Comment by tbigueres** [comment]
I tried again the brew uninstall and reinstall, but still nothing happens. 
@rderik

**Comment by rderik** [comment]
Oh yea,

When I did the new formula I didn't include the zsh autocomplete, only bash and fishshell :S 
That's why is not working for you on zsh. I'll have to check if there is a zsh autocomplete and add it to the formula and ask for a pull request for it. I'll update you if I figure that out.

And for your friend it might be a good idea to update his bash, that is an outdated bash maybe the autocomplete only works on newer versions you can ask him to try a newer version of bash the one in homebrew is: 4.4.12 tell him to try that one and let me know if it works for him.
