### ISSUE TITLE
lpass login: Error: SSL peer certificate or SSH remote key was not OK.

### ISSUE THREAD

**Issue by hansmannaerts** [lastpass/lastpass-cli#540]
Hi,

I am trying to use lastpass-cli on cygwin but everytime i try to login i get:
Error: SSL peer certificate or SSH remote key was not OK.

What could be the reason of this error?

Mvg,
Hans Mannaerts

**Comment by loalf** [comment]
I'm having the same issue

**Comment by chrisschaaf** [comment]
I resolved this by reinstalling openssl. `brew reinstall openssl@1.1` - might see if that works for you!

**Comment by abhijitpjoshi** [comment]
I am getting the same error and brew reinstall openssl@1.1 couldn't fix it. Can someone help?

**Comment by isagarsarkar** [comment]
I am also facing same issue with openssl@3

**Comment by rh310108** [comment]
I am having the same issue. 
I have tried reinstall openssl@1.1 and reinstall lastpass-cli.

**Comment by rh310108** [comment]
I noticed that the openssl@1.1 is dependant on ca-certificates package. 
`brew info openssl@1.1
openssl@1.1: stable 1.1.1m (bottled) [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
/usr/local/Cellar/openssl@1.1/1.1.1m (8,081 files, 18.5MB)
  Poured from bottle on 2021-12-20 at 09:22:24
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/openssl@1.1.rb
License: OpenSSL
==> Dependencies
Required: ca-certificates ✔`
I went forward and reinstalled the ca-certificates package. The issue is resolved now

**Comment by ttoennies** [comment]
I'm getting this error as well.  Tried the suggestions noted above but those packages are already installed.  My account is setup for MFA; could that be the cause?  Any suggestions are appreciated, thank you.

**Comment by bormosLP** [comment]
1.3.6 release has the fix for this issue.
