### ISSUE TITLE
add encrypted output of function 'export'

### ISSUE THREAD

**Issue by bartekww** [lastpass/lastpass-cli#74]
as instead plain text. We need more safety. Anyone can read our passwords now. AES256 should be fine.

**Comment by bcopeland** [comment]
I replied via email but I think it got lost.  What's the attack model here?  I think any encryption we do here would not add real security since a user that can connect to the agent to export can see your passwords anyway.

You can use "lpass export | gpg" to encrypt at rest, and you can set any password to reprompt through the web ui to force MPW reprompt before export dumps the plaintext, to prevent casual drive-by snooping.

**Comment by bcopeland** [comment]
In the absence of a really compelling use-case, I don't think I want to add something extra here when gpg can do the job.
